const express = require('express');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const { v4: uuidv4 } = require('uuid');
const { jsPDF } = require('jspdf');
const authMiddleware = require('../middleware/auth');
const db = require('../models/database');

const router = express.Router();

// Configure multer for file uploads
const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    const uploadDir = path.join(__dirname, '../../uploads');
    if (!fs.existsSync(uploadDir)) {
      fs.mkdirSync(uploadDir, { recursive: true });
    }
    cb(null, uploadDir);
  },
  filename: (req, file, cb) => {
    const uniqueName = uuidv4() + path.extname(file.originalname);
    cb(null, uniqueName);
  }
});

const upload = multer({ 
  storage,
  fileFilter: (req, file, cb) => {
    const allowedTypes = ['.pdf', '.md', '.txt'];
    const ext = path.extname(file.originalname).toLowerCase();
    if (allowedTypes.includes(ext)) {
      cb(null, true);
    } else {
      cb(new Error('Invalid file type. Only PDF, Markdown, and text files are allowed.'));
    }
  },
  limits: { fileSize: 10 * 1024 * 1024 } // 10MB limit
});

// Upload document
router.post('/upload', authMiddleware, upload.single('document'), (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No file uploaded' });
    }

    const { filename, originalname, mimetype, size } = req.file;
    const userId = req.user.userId;
    const fileType = path.extname(originalname).toLowerCase();

    // Save document info to database
    db.run(
      'INSERT INTO documents (user_id, filename, original_name, file_type, file_size) VALUES (?, ?, ?, ?, ?)',
      [userId, filename, originalname, fileType, size],
      function(err) {
        if (err) {
          console.error(err);
          return res.status(500).json({ error: 'Failed to save document' });
        }

        res.status(201).json({
          message: 'Document uploaded successfully',
          document: {
            id: this.lastID,
            filename: originalname,
            fileType,
            size,
            uploadedAt: new Date().toISOString()
          }
        });
      }
    );
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Upload failed' });
  }
});

// Generate sample documentation (for demo purposes)
router.post('/generate', authMiddleware, async (req, res) => {
  try {
    const { title, content, format } = req.body;
    const userId = req.user.userId;

    if (!title || !content || !format) {
      return res.status(400).json({ error: 'Title, content, and format are required' });
    }

    let filename, fileType, filePath;
    const uploadDir = path.join(__dirname, '../../uploads');

    if (format === 'pdf') {
      // Generate PDF
      const doc = new jsPDF();
      doc.setFontSize(20);
      doc.text(title, 20, 30);
      doc.setFontSize(12);
      
      // Split content into lines to fit PDF
      const lines = doc.splitTextToSize(content, 170);
      doc.text(lines, 20, 50);
      
      filename = uuidv4() + '.pdf';
      filePath = path.join(uploadDir, filename);
      fileType = '.pdf';
      
      doc.save(filePath);
    } else if (format === 'markdown') {
      // Generate Markdown
      const markdownContent = `# ${title}\n\n${content}\n\n---\n*Generated by Azure Portal Analyzer*`;
      filename = uuidv4() + '.md';
      filePath = path.join(uploadDir, filename);
      fileType = '.md';
      
      fs.writeFileSync(filePath, markdownContent);
    } else {
      return res.status(400).json({ error: 'Invalid format. Use "pdf" or "markdown"' });
    }

    const stats = fs.statSync(filePath);
    const originalName = `${title.replace(/[^a-zA-Z0-9]/g, '_')}${fileType}`;

    // Save document info to database
    db.run(
      'INSERT INTO documents (user_id, filename, original_name, file_type, file_size) VALUES (?, ?, ?, ?, ?)',
      [userId, filename, originalName, fileType, stats.size],
      function(err) {
        if (err) {
          console.error(err);
          return res.status(500).json({ error: 'Failed to save document' });
        }

        res.status(201).json({
          message: 'Document generated successfully',
          document: {
            id: this.lastID,
            filename: originalName,
            fileType,
            size: stats.size,
            createdAt: new Date().toISOString()
          }
        });
      }
    );
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Generation failed' });
  }
});

// List user's documents
router.get('/', authMiddleware, (req, res) => {
  const userId = req.user.userId;

  db.all(
    'SELECT id, original_name, file_type, file_size, created_at FROM documents WHERE user_id = ? ORDER BY created_at DESC',
    [userId],
    (err, documents) => {
      if (err) {
        console.error(err);
        return res.status(500).json({ error: 'Failed to fetch documents' });
      }

      res.json({ documents });
    }
  );
});

// Delete document
router.delete('/:id', authMiddleware, (req, res) => {
  const documentId = req.params.id;
  const userId = req.user.userId;

  // First get the document to delete the file
  db.get(
    'SELECT filename FROM documents WHERE id = ? AND user_id = ?',
    [documentId, userId],
    (err, document) => {
      if (err) {
        console.error(err);
        return res.status(500).json({ error: 'Database error' });
      }

      if (!document) {
        return res.status(404).json({ error: 'Document not found' });
      }

      // Delete the file
      const filePath = path.join(__dirname, '../../uploads', document.filename);
      if (fs.existsSync(filePath)) {
        fs.unlinkSync(filePath);
      }

      // Delete from database
      db.run(
        'DELETE FROM documents WHERE id = ? AND user_id = ?',
        [documentId, userId],
        function(err) {
          if (err) {
            console.error(err);
            return res.status(500).json({ error: 'Failed to delete document' });
          }

          res.json({ message: 'Document deleted successfully' });
        }
      );
    }
  );
});

module.exports = router;